--
-- PostgreSQL database dump
--

\restrict IVXcTCzw5MhIfSmdHQp27H5QRAtK4DNL0XGoUbaaxfyhOFbcEwZaNwpnc87du19

-- Dumped from database version 15.18 (Homebrew)
-- Dumped by pg_dump version 15.18 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: colleges; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.colleges (
    id bigint NOT NULL,
    city character varying(255),
    name character varying(255) NOT NULL,
    state character varying(255)
);


ALTER TABLE public.colleges OWNER TO postgres;

--
-- Name: colleges_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.colleges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.colleges_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.courses (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.courses OWNER TO postgres;

--
-- Name: courses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.courses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: insiders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.insiders (
    id bigint NOT NULL,
    account_holder_name character varying(255),
    admin_summary character varying(1000),
    bio character varying(500),
    college character varying(255),
    college_id_number character varying(255),
    course character varying(255),
    custom_course character varying(255),
    email character varying(255) NOT NULL,
    full_name character varying(255),
    linked_in_url character varying(255),
    onboarding_watched boolean NOT NULL,
    phone character varying(255),
    photo_path character varying(255),
    registered_at timestamp(6) without time zone,
    upi_id character varying(255),
    upi_verification_status character varying(255),
    upi_verified_at timestamp(6) without time zone,
    year character varying(255),
    edu_email character varying(255),
    id_card_path character varying(255),
    otp_code character varying(255),
    proof_of_admission_path character varying(255),
    verification_method character varying(255),
    edu_email_verified boolean
);


ALTER TABLE public.insiders OWNER TO postgres;

--
-- Name: insiders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.insiders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insiders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mentors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mentors (
    id bigint NOT NULL,
    admin_summary character varying(1000),
    area_of_expertise character varying(255),
    bio character varying(500),
    company character varying(255),
    designation character varying(255),
    email character varying(255) NOT NULL,
    full_name character varying(255),
    linked_in_url character varying(255),
    onboarding_watched boolean NOT NULL,
    phone character varying(255),
    photo_path character varying(255),
    registered_at timestamp(6) without time zone,
    work_email character varying(255),
    years_of_experience integer,
    otp_code character varying(255),
    upi_id character varying(255),
    upi_verification_status character varying(255),
    verification_method character varying(255),
    work_email_verified boolean,
    employee_id_card_path character varying(255),
    proof_of_work_path character varying(255)
);


ALTER TABLE public.mentors OWNER TO postgres;

--
-- Name: mentors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mentors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mentors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: students; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.students (
    id bigint NOT NULL,
    account_holder_name character varying(255),
    city character varying(255),
    college character varying(255),
    college_email character varying(255),
    course character varying(255),
    custom_course character varying(255),
    email character varying(255) NOT NULL,
    full_name character varying(255),
    linked_in_url character varying(255),
    phone character varying(255),
    photo_path character varying(255),
    registered_at timestamp(6) without time zone,
    upi_id character varying(255),
    upi_verification_status character varying(255),
    upi_verified_at timestamp(6) without time zone,
    year character varying(255)
);


ALTER TABLE public.students OWNER TO postgres;

--
-- Name: students_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: colleges colleges_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.colleges
    ADD CONSTRAINT colleges_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: insiders insiders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.insiders
    ADD CONSTRAINT insiders_pkey PRIMARY KEY (id);


--
-- Name: mentors mentors_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentors
    ADD CONSTRAINT mentors_pkey PRIMARY KEY (id);


--
-- Name: students students_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);


--
-- Name: mentors uk3bc7865sx3tvbu45750dk6nrc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentors
    ADD CONSTRAINT uk3bc7865sx3tvbu45750dk6nrc UNIQUE (work_email);


--
-- Name: colleges uk4q2vsgb93d2wyblodej8r5hmc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.colleges
    ADD CONSTRAINT uk4q2vsgb93d2wyblodej8r5hmc UNIQUE (name);


--
-- Name: mentors uk55bw97ycqmsaom05yph7d6373; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mentors
    ADD CONSTRAINT uk55bw97ycqmsaom05yph7d6373 UNIQUE (email);


--
-- Name: courses uk5o6x4fpafbywj4v2g0owhh11r; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT uk5o6x4fpafbywj4v2g0owhh11r UNIQUE (name);


--
-- Name: students uke2rndfrsx22acpq2ty1caeuyw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uke2rndfrsx22acpq2ty1caeuyw UNIQUE (email);


--
-- Name: insiders ukhtrotrmxjydla86r19yvrlngi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.insiders
    ADD CONSTRAINT ukhtrotrmxjydla86r19yvrlngi UNIQUE (email);


--
-- PostgreSQL database dump complete
--

\unrestrict IVXcTCzw5MhIfSmdHQp27H5QRAtK4DNL0XGoUbaaxfyhOFbcEwZaNwpnc87du19

