package com.asksenior.controller;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import software.amazon.awssdk.services.s3.model.GetObjectRequest;
import software.amazon.awssdk.services.s3.presigner.S3Presigner;
import software.amazon.awssdk.services.s3.presigner.model.GetObjectPresignRequest;
import software.amazon.awssdk.services.s3.presigner.model.PresignedGetObjectRequest;

import java.net.URI;
import java.time.Duration;

@RestController
@RequestMapping("/api/files")
public class FileController {

    private final S3Presigner s3Presigner;

    @Value("${aws.s3.bucket}")
    private String bucketName;

    // Allow only the exact key format generated by FileStorageService:
    // <role>_<id>_<prefix>_<12-char-uuid>.<ext>
    // e.g.  insider_42_photo_a1b2c3d4e5f6.jpg
    private static final java.util.regex.Pattern SAFE_KEY =
            java.util.regex.Pattern.compile("^[a-zA-Z0-9_\\-]{1,200}\\.(jpg|jpeg|png|pdf)$");

    public FileController(S3Presigner s3Presigner) {
        this.s3Presigner = s3Presigner;
    }

    @GetMapping("/{key}")
    public ResponseEntity<Void> getFileUrl(@PathVariable String key) {
        // Reject any key that doesn't match the expected safe pattern
        if (!SAFE_KEY.matcher(key).matches()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }

        try {
            GetObjectRequest getObjectRequest = GetObjectRequest.builder()
                    .bucket(bucketName)
                    .key(key)
                    .build();

            GetObjectPresignRequest presignRequest = GetObjectPresignRequest.builder()
                    .signatureDuration(Duration.ofMinutes(15))
                    .getObjectRequest(getObjectRequest)
                    .build();

            PresignedGetObjectRequest presignedRequest = s3Presigner.presignGetObject(presignRequest);
            String url = presignedRequest.url().toString();

            return ResponseEntity.status(HttpStatus.FOUND)
                    .location(URI.create(url))
                    .build();
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).build();
        }
    }
}
